# Generated by Django 3.2.8 on 2021-11-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='zip_code',
        ),
    ]
