# Generated by Django 3.2.8 on 2021-11-05 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('company_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=25)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.company')),
            ],
        ),
    ]
